spring:
  datasource:
    url: jdbc:h2:mem:custom-security
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update # application 실행 시 기존 테이블 drop 후 create
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug # 발생되는 쿼리문을 로그로 출력

jwt:
  secret-key: bc1468be411fc43d78ca5310d3ff4b75a20a4d3758c3b65cf8588e04a5e09585477afdd260f6660a4378432e1db3a5f305b86fbe78b69c08d85410b8381ae2ca
  expiration-time: 86400000  #토크 만료 시간
  issuer: hope # 토근 발급자